# Site settings
title: Gaurav Hulmukh
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gaurav Hulmukh 
user_description:
user_title: Computer Engineer, Android Developer,Data Scientist enthusiast, Web & Code Fanatic
email: ghulmukh10@gmail.com
twitter_username: 
github_username:  Gauravhulmukh
facebook_username: Gaurav Hulmukh
gplus_username: 
linkedin_username: gaurav-hulmukh-932648166

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
